/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrashTransactionsRouteImport } from './routes/trash/transactions'
import { Route as TrashCategoriesRouteImport } from './routes/trash/categories'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashTransactionsRoute = TrashTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => TrashRoute,
} as any)
const TrashCategoriesRoute = TrashCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => TrashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trash': typeof TrashRouteWithChildren
  '/trash/categories': typeof TrashCategoriesRoute
  '/trash/transactions': typeof TrashTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trash': typeof TrashRouteWithChildren
  '/trash/categories': typeof TrashCategoriesRoute
  '/trash/transactions': typeof TrashTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trash': typeof TrashRouteWithChildren
  '/trash/categories': typeof TrashCategoriesRoute
  '/trash/transactions': typeof TrashTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/recurring'
    | '/settings'
    | '/transactions'
    | '/trash'
    | '/trash/categories'
    | '/trash/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/recurring'
    | '/settings'
    | '/transactions'
    | '/trash'
    | '/trash/categories'
    | '/trash/transactions'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/recurring'
    | '/settings'
    | '/transactions'
    | '/trash'
    | '/trash/categories'
    | '/trash/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoriesRoute: typeof CategoriesRoute
  RecurringRoute: typeof RecurringRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TrashRoute: typeof TrashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash/transactions': {
      id: '/trash/transactions'
      path: '/transactions'
      fullPath: '/trash/transactions'
      preLoaderRoute: typeof TrashTransactionsRouteImport
      parentRoute: typeof TrashRoute
    }
    '/trash/categories': {
      id: '/trash/categories'
      path: '/categories'
      fullPath: '/trash/categories'
      preLoaderRoute: typeof TrashCategoriesRouteImport
      parentRoute: typeof TrashRoute
    }
  }
}

interface TrashRouteChildren {
  TrashCategoriesRoute: typeof TrashCategoriesRoute
  TrashTransactionsRoute: typeof TrashTransactionsRoute
}

const TrashRouteChildren: TrashRouteChildren = {
  TrashCategoriesRoute: TrashCategoriesRoute,
  TrashTransactionsRoute: TrashTransactionsRoute,
}

const TrashRouteWithChildren = TrashRoute._addFileChildren(TrashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  CategoriesRoute: CategoriesRoute,
  RecurringRoute: RecurringRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TrashRoute: TrashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
